title = "앱 개발 블로그"
baseurl = "https://app.majorika.net"
languageCode = "ko"
theme = "kiera"
canonifyurls = true
copyright = "Copyright &copy; 2021 - majorika"
DefaultContentLanguage = "ko"

paginate = 5

summaryLength = 30
pygmentsCodeFences = true
enableEmoji = true

[author]
    name = "majorika"
    github = "majorika"
    twitter = "majorika"
    instagram = "majorika_"

[params]
    tagline = "이런 저런 개발 이야기가 적히는 곳입니다"
    description = "이런 저런 개발 이야기가 적히는 곳입니다."
